spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
  jmx:
    enabled: false
logging:
  level:
    sun.rmi.transport.tcp: ERROR
